# Generated by Django 3.2 on 2022-06-30 00:18

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ('-nama',), 'verbose_name_plural': 'kategori'},
        ),
        migrations.AlterModelOptions(
            name='produk',
            options={'ordering': ('-nama',), 'verbose_name_plural': 'Produk'},
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(upload_to=listings.models.Produk.lokasi_ganti_nama),
        ),
    ]
